<?php

namespace NM\TrelloBundle\Entity;

/**
 * tachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tachesRepository extends \Doctrine\ORM\EntityRepository
{
}
