nm_user:
    resource: "@NMUserBundle/Resources/config/routing.yml"
    prefix:   /

nm_trello:
    resource: "@NMTrelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: /index
    defaults: {_controller: NMTrelloBundle:Default:index}

homepage:
    path: /
    defaults: {_controller: FOSUserBundle:Registration:register}
