nm_trello_taches:
    resource: "@NMTrelloBundle/Resources/config/routing/taches.yml"
    prefix:   /taches

nm_trello_projets:
    resource: "@NMTrelloBundle/Resources/config/routing/projets.yml"
    prefix:   /projets


